// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhOVce8352lCWfGS5ktn3eRE4vmEzPN4',
    appId: '1:760010790817:web:e8b11f47896d33e1569de0',
    messagingSenderId: '760010790817',
    projectId: 'mobile-inventory-system-test',
    authDomain: 'mobile-inventory-system-test.firebaseapp.com',
    storageBucket: 'mobile-inventory-system-test.firebasestorage.app',
    measurementId: 'G-7L3TGNWNJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANA-7QnA21vM-ZSjbP-2fBMkv5b_USP5Y',
    appId: '1:760010790817:android:1caa08539f159ab8569de0',
    messagingSenderId: '760010790817',
    projectId: 'mobile-inventory-system-test',
    storageBucket: 'mobile-inventory-system-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Nb3XK3dOM_Mnn8ki1xFKwkCw7u4km9c',
    appId: '1:760010790817:ios:6de6a7d101560654569de0',
    messagingSenderId: '760010790817',
    projectId: 'mobile-inventory-system-test',
    storageBucket: 'mobile-inventory-system-test.firebasestorage.app',
    iosBundleId: 'com.example.mobileInventory',
  );
}
